// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileDownload.proto

package com.li.rpc;

public final class FileDownloadApi {
  private FileDownloadApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_TargetFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_TargetFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_FileInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022FileDownload.proto\022\ncom.li.rpc\"\036\n\nTarg" +
      "etFile\022\020\n\010filename\030\001 \001(\t\"9\n\010FileInfo\022\020\n\010" +
      "filename\030\001 \001(\t\022\r\n\005index\030\002 \001(\005\022\014\n\004arrs\030\003 " +
      "\001(\0142J\n\nRouteGuide\022<\n\010download\022\026.com.li.r" +
      "pc.TargetFile\032\024.com.li.rpc.FileInfo\"\0000\001B" +
      "\037\n\ncom.li.rpcB\017FileDownloadApiP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_li_rpc_TargetFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_li_rpc_TargetFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_TargetFile_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_com_li_rpc_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_li_rpc_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_FileInfo_descriptor,
        new java.lang.String[] { "Filename", "Index", "Arrs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
