// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileDownload.proto

package com.li.rpc;

public interface FileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.FileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文件名
   * </pre>
   *
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <pre>
   * 文件名
   * </pre>
   *
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * 文件块数
   * </pre>
   *
   * <code>int32 index = 2;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <pre>
   * 文件字节数据
   * </pre>
   *
   * <code>bytes arrs = 3;</code>
   * @return The arrs.
   */
  com.google.protobuf.ByteString getArrs();
}
