// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileDownload.proto

package com.li.rpc;

public interface TargetFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.TargetFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
